### ISSUE TITLE
Use class to style elements

### ISSUE THREAD

**Issue by cyouh95** [rawitscher/Dasmotos#2]
Alternatively, you could add a `class` to the `strong` elements and use that as your selector the style these price texts. That way, in case you want to use the `strong` tag for something else later, they won't all already be styled blue.

HTML:
```html
<strong class="price">Starting at $3.00 / brush.</strong>
```

CSS:
```css
.price { 
  color: blue;
}
```

https://github.com/rawitscher/Dasmotos/blob/master/index.html#L19
https://github.com/rawitscher/Dasmotos/blob/master/resources/style.css#L24-L26

**Comment by rawitscher** [comment]
I didn't think about that. Thank you for the tip!
