### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [rawitscher/Dasmotos#4]
(Exceeds Expectations)

Nice job with this project! It looks like you have a good understanding of how HTML and CSS work together for display of content. You were able to recreate all the main components of this webpage so well done! 

In addition, your code was very efficient in selecting the elements to style (#3). Great attention to detail as well, such as remembering to include [backup font families](https://github.com/rawitscher/Dasmotos/blob/master/resources/style.css#L2) and the`img` [alt attribute](https://github.com/rawitscher/Dasmotos/blob/master/index.html#L13)!

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Happy coding!

**Comment by rawitscher** [comment]
Thank you for the advice!! I'll work on building from scratch this week :)
